const Actions = {
  GET_LIST_QUESTION : "GET_LIST_QUESTION",
  GET_RESULT : "GET_RESULT",
  ON_SELECTED_ANSWER : "ON_SELECTED_ANSWER",
  ON_NEXT_QUESTION : "ON_NEXT_QUESTION",
  ON_PREV_QUESTION: "ON_PREV_QUESTION",
  ON_START_TIME : "ON_START_TIME",
  GAME_OVER : "GAME_OVER"
}


export default Actions